### ISSUE TITLE
Consider adding golangci-lint

### ISSUE THREAD

**Issue by felixhromadko** [dokedu/dokedu#45]
[golangci-lint](https://golangci-lint.run/) is a Go linter aggregator that provides easy and quick access to a set of configurable Go linters that inspect the code and issue various warnings, ultimately helping to write better Go code.

A couple of examples:
```
internal/middleware/auth.go:43:8: ineffectual assignment to err (ineffassign)
                                _, err = bun.NewUpdate().Model(&session).Set("deleted_at = ?", time.Now()).Where("id = ?", session.ID).Exec(c.Request().Context())
```
(not checking the error)

```
internal/services/report_generation/generator/pdf/helper.go:50:2: S1021: should merge variable declaration with assignment on next line (gosimple)
        var ioReader io.Reader
```
(simplify the code)

```
internal/mail/template.go:61:9: S1025: should use String() instead of fmt.Sprintf (gosimple)
        return fmt.Sprintf("%s", out), nil
```
(parsing the format template is expensive, and since it does not contain anything other than `%s`, it can be replaced with String())

If you feel like this is a valuable addition to the project, feel free to assign this issue to me!

**Comment by tomhaerter** [comment]
hey @felixhromadko, this is a great addition to improve code quality and most likely security. I have assigned it to you and thank you for suggesting it!
