### ISSUE TITLE
Use errorpresenter instead of  graphql.AddError

### ISSUE THREAD

**Issue by felixhromadko** [dokedu/dokedu#51]
If we need to return a graphql error with a code extension, we are currently using this:
```
graphql.AddError(ctx, &gqlerror.Error{
	Message: "no user found in the context",
	Extensions: map[string]interface{}{
		"code": "UNAUTHENTICATED",
	},
})
return nil, errors.New("no user found in the context")
```

There are a couple of issues with this approach:
* pretty verbose
* requires graphql middlewares to have run
* hard to test for it
* codes aren't constants, not defined in a single place

I suggest that we should use the [ErrorPresenter](https://gqlgen.com/reference/errors/#the-error-presenter) to accomplish this.

This would allow us to define errors like this in a single place:
```
var (
	//normal errors, without code
	ErrInvalidEmailOrPassword = errors.New("invalid email or password")

	// errors with code
	ErrUnauthorized = ErrWithCode("UNAUTHORIZED", "no user found in the context")
)
```
And use it like this everywhere:
```
return msg.ErrUnauthorized
```
 
 or test it like this:
 ```
_, err := login("invalid", "invalid")
ts.ErrorIs(err, msg.ErrInvalidEmailOrPassword)
 ```
 
 and the errorPresenter will automatically add the extensions -> code, if necessary.
 
 Currently working on a pr that introduces a small testing framework, if you want to see this idea in action I'd be happy to include this change in there.

**Comment by tomhaerter** [comment]
I have wanted to tackle error handling for a long time, but never got around to it. So thanks for suggesting the changes and also pointing out the benefits. I would love to see this idea in action!
